### ISSUE TITLE
Plz halp: portal release notes not showing up on the web page

### ISSUE THREAD

**Issue by staceybuckelew** [axiom-data-science/axiom-data-science.github.io#18]
I don;t know what I am doing wrong here. Also, I have never published an issue in Git, so we'll see if anyone responds to this...

I committed these changes to the portal release notes: _portal-updates/2019-11-01-2.11-release-notes.md

They don't appear to be showing up on the release notes landing page. Not sure why.... what am I doing wrong?

https://axiomdatascience.com/portal-updates/

Plz halp.

**Comment by srstsavage** [comment]
@staceybuckelew Does it look right [now](https://axiomdatascience.com/portal-updates/)?

You had a newline at the top of the document that was breaking the parsing.

https://github.com/axiom-data-science/axiom-data-science.github.io/commit/f3656ce32998b991ff0a14031564e5911a539faa

**Comment by staceybuckelew** [comment]
Yep, looks good! Thanks for fixing. This is completely my own ignornace, but I didn't see any type of error message indicating what was broken...
