### ISSUE TITLE
Broken headshot for Lauren

### ISSUE THREAD

**Issue by staceybuckelew** [axiom-data-science/axiom-data-science.github.io#20]
https://www.axiomdatascience.com/about/

Not sure what I am doing wrong here, but image broken on staff page. Plz halp.

**Comment by kwilcox** [comment]
All other headshots are .jpg, that’s likely assumed somewhere!

**Comment by akbstone** [comment]
[image: l-showalter.png]

**Comment by akbstone** [comment]
should be fixed in a few

**Comment by staceybuckelew** [comment]
duh!! Thank you!
